import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/context/themeContext";

export const metadata = {
  title: "Portfolio-Dashboard",
  description: "Generated by David Pal",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider>
          <div>
            <div>
              <Navbar />
            </div>
            <div>
              <Sidebar />
            </div>
            <main>{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
